### ISSUE TITLE
Re-implement moz-os-version for Windows 10

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#1]
[1166867] (https://bugzilla.mozilla.org/show_bug.cgi?id=1166867).

**Comment by trav90** [comment]
Looks like this is already in our code?

**Comment by wolfbeast** [comment]
It is? I thought that FF40 or thereabouts.

**Comment by trav90** [comment]
Yup it landed in FF41, but was also back-ported by Mozilla to ESR 38. Both patches posted in 1166867 are already in our tree.

**Comment by wolfbeast** [comment]
Oh, great then! Closing.
