### ISSUE TITLE
Update OTS to 5.0 + import Google WOFF2 module

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#101]
We should update the OTS to 5.0. Since this no longer supplies woff2 decoding itself and relies on Google's module to provide WOFF2 decoding as a submodule from that point forward, we'll also have to import the Google WOFF2 module into our tree separately (to `/modules/woff2`) and make sure we grab an updated copy occasionally to stay ahead of any code issues.

**Comment by wolfbeast** [comment]
Relevant BMO bug https://bugzilla.mozilla.org/show_bug.cgi?id=1227058
This should be fairly straight-forward; feel free to take this if you have a few spare hours.

**Comment by trav90** [comment]
I'd be willing to take this.

**Comment by wolfbeast** [comment]
Assigned you to it - we most likely want to get a more recent version of the woff2 code from the github repo than in that BMO bug for sec reasons.

**Comment by trav90** [comment]
:+1:

**Comment by wolfbeast** [comment]
Verified working as-intended.
