### ISSUE TITLE
Fix up DOM Ruby RTL positioning

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#13]
We probably want to use the DOM implementation of Ruby Annotations instead of the integrated extension code. But to do this, we'd need to fix these annotations for bidi and RTL text.

Relevant bugzilla bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1141928 (RTL)

The dependent bug https://bugzilla.mozilla.org/show_bug.cgi?id=1141931 (bidi) was uplifted so is already in our tree.

**Comment by wolfbeast** [comment]
Well, some things got fixed, including a poor CSS 2 bug, and as it turns out the bidi bug was *not* uplifted after all despite the "fixed" flag, so that needs to go in to address this.

**Comment by TPS** [comment]
Would updating the backend extension code as mentioned in https://github.com/sakai135/htmlruby-firefox/issues/3#issuecomment-202466810 address this, also?

**Comment by wolfbeast** [comment]
The extension code is completely separate from this implementation, and already renders this correctly in its current state.
If *this* implementation is completed, then the core will have built-in ruby annotations support directly in the parser -- although the extension is of course more flexible in what it can do provided it remains maintained (in which case we may want to keep the back-end extension solution instead of a core solution).

There's a balance needed here to make a choice for either/both:
- The core implementation will be faster by several magnitudes, but less flexible unless a lot more work goes into implementing ruby styles, which might be a back-burner deal indefinitely if we don't get someone who is willing to contribute to this module.
- The extension implementation is easier to maintain and more flexible, and can be switched off by the majority of people who won't need this. But it's slower and possibly not compatible with some sites.

The question will therefore have to be: can we expect @sakai135 to update and maintain his extension code for our integration after the re-base?

**Comment by wolfbeast** [comment]
Sakai135 was clear that HTML Ruby will not be supported or maintained any further, meaning we will continue with this parser-integrated Ruby implementation for Tycho.
The integrated extension code is sufficient for v26.* (I haven't heard any complaints from Ruby Annotations users) and the parser-based one will be able to use basic ruby-* css keywords, which according to Sakai135 accounts for just about all practical use of Ruby Annotations.

Once this RTL/bidirectional issue is fixed, that should be about all that's needed.

**Comment by wolfbeast** [comment]
Verification page for proper ruby support:
http://www.i18nguy.com/unicode/unicode-example-ruby.html
