### ISSUE TITLE
Build failure when using LTO/LTCG

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/Tycho#15]
Tycho fails on building ICU with GCC 4.9 (and possibly earlier versions) when Link Time Optimization is used. GCC 5.x is not affected.

Mozilla's solution is to revamp the ICU build system and stop using autoconf for it. While not critical, it would be nice to have LTO working with versions of GCC below 5.0.

BMO bugs: [1000689](https://bugzilla.mozilla.org/show_bug.cgi?id=1000689) & [1239083](https://bugzilla.mozilla.org/show_bug.cgi?id=1239083)

**Comment by wolfbeast** [comment]
ICU is a disaster in more ways than one; unfortunately we're pretty much stuck with it because Mozilla has moved from own code to being Mozilla-glue. We can still build with the previous i10n code and disable ICU, but that will not provide support for e.g. ECMA-402 (since that's built solely on ICU).

**Comment by wolfbeast** [comment]
I had a quick look at the ICU build system change Mozilla made for Firefox 48, and it (1) doesn't apply to Tycho's code without completely rewriting it and (2) seems like a hack, and an ugly one, to just provide semi-precompiled binary code instead of building from source in-tree.

Maybe http://hubicka.blogspot.se/2014/04/linktime-optimization-in-gcc-2-firefox.html has some better workarounds for LTO build failures, but I'd rather make this kind of compiler error NOT severely impact our source tree.

**Comment by mattatobin** [comment]
Can't you selectively disable LTO for ICU?

**Comment by trav90** [comment]
Good point; yes that should be possible. I'll test it and report back.

**Comment by trav90** [comment]
I've gotten a LTO build to progress further by disabling LTO for ICU, however now I'm hitting bustage in XPCOM

```
22:52.39 /tmp/ccoh5Adh.ltrans0.ltrans.o: In function `main':
22:52.39 /home/trava90/PaleMoon/Tycho/Tycho/xpcom/sample/program/nsTestSample.cpp:29: undefined reference to `XPCOMGlueStartup'
22:52.39 /tmp/ccoh5Adh.ltrans0.ltrans.o: In function `StartAssignment':
22:52.39 /home/trava90/PaleMoon/Tycho/pmbuild/xpcom/sample/program/../../../dist/include/nsCOMPtr.h:717: undefined reference to `nsCOMPtr_base::begin_assignment()'
22:52.40 /tmp/ccoh5Adh.ltrans0.ltrans.o: In function `main':
22:52.40 /home/trava90/PaleMoon/Tycho/Tycho/xpcom/sample/program/nsTestSample.cpp:33: undefined reference to `NS_InitXPCOM2'
22:52.40 /tmp/ccoh5Adh.ltrans0.ltrans.o: In function `__base_ctor ':
22:52.40 /home/trava90/PaleMoon/Tycho/pmbuild/xpcom/sample/program/../../../dist/include/nsCOMPtr.h:482: undefined reference to `nsCOMPtr_base::assign_from_qi(nsQueryInterface, nsID const&)'
22:52.40 /tmp/ccoh5Adh.ltrans0.ltrans.o: In function `StartAssignment':
22:52.40 /home/trava90/PaleMoon/Tycho/pmbuild/xpcom/sample/program/../../../dist/include/nsCOMPtr.h:717: undefined reference to `nsCOMPtr_base::begin_assignment()'
22:52.40 /tmp/ccoh5Adh.ltrans0.ltrans.o: In function `main':
22:52.40 /home/trava90/PaleMoon/Tycho/Tycho/xpcom/sample/program/nsTestSample.cpp:88: undefined reference to `NS_Free'
22:52.40 /tmp/ccoh5Adh.ltrans0.ltrans.o: In function `operator=':
22:52.40 /home/trava90/PaleMoon/Tycho/pmbuild/xpcom/sample/program/../../../dist/include/nsCOMPtr.h:546: undefined reference to `nsCOMPtr_base::assign_with_AddRef(nsISupports*)'
22:52.40 /home/trava90/PaleMoon/Tycho/pmbuild/xpcom/sample/program/../../../dist/include/nsCOMPtr.h:546: undefined reference to `nsCOMPtr_base::assign_with_AddRef(nsISupports*)'
22:52.40 /home/trava90/PaleMoon/Tycho/pmbuild/xpcom/sample/program/../../../dist/include/nsCOMPtr.h:546: undefined reference to `nsCOMPtr_base::assign_with_AddRef(nsISupports*)'
22:52.40 /tmp/ccoh5Adh.ltrans0.ltrans.o: In function `main':
22:52.40 /home/trava90/PaleMoon/Tycho/Tycho/xpcom/sample/program/nsTestSample.cpp:100: undefined reference to `NS_ShutdownXPCOM'
22:52.40 /opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: nsTestSample: hidden symbol `NS_ShutdownXPCOM' isn't defined
22:52.40 /opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: final link failed: Bad value
22:52.40 collect2: error: ld returned 1 exit status
22:52.40 gmake[5]: *** [nsTestSample] Error 1
22:52.41 gmake[4]: *** [xpcom/sample/program/target] Error 2
```

**Comment by trav90** [comment]
Been looking into this some more, and I'm thinking that the problem is something specific to the devtoolset GCC packages (or CentOS 6). As mentioned in the first post, ICU built fine with GCC 5 & LTO on my Manjaro box, but building on CentOS 6 with GCC 5.3 (from devtoolset-4) with LTO, the build fails with the exact errors as with GCC 4.9 (from devtoolset-3, and also on CentOS 6).

**Comment by wolfbeast** [comment]
These kinds of errors indicate compiled-code instability. If you're testing it on the compile box, then your kernel will be different as well.
For the record, Tycho doesn't like LTCG (link-time code generation) in MSVC either, and actually causes an internal compiler error if attempted on my workstation. So there's some code complexity in Tycho's code base right now that causes issues in both MSVC and gcc when trying to use link-time compilation (gcc LTO does something similar IIUC).

Although a nice thing to aim for, our code size likely won't benefit from LTO nearly as much as smaller programs would. So, likely it's not worth the headaches at the moment.

**Comment by trav90** [comment]
> Although a nice thing to aim for, our code size likely won't benefit from LTO nearly as much as smaller programs would. So, likely it's not worth the headaches at the moment.

Agreed.

**Comment by wolfbeast** [comment]
It's quite possible this will improve if we work on reducing code complexity (which I do plan to tackle once we have a working base). Mozilla has been piling on overload upon overload and redirect upon redirect, even more so with their e10s work. I'm not surprised if a compiler gets confused by literally having billions of function calls to group together, sort, categorize, resolve dependencies of and compile in a single stage.

**Comment by trav90** [comment]
Sounds good :+1:
