### ISSUE TITLE
Make the proper changes for devtools

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#25]
Tracking the devtools component specifically:

- [x] Create devtools work branch
- [x] Put devtools-38 in place
- [x] Make theme style changes for devtools-38
- [x] Go through front-end calls and adjust calls where necessary
- [ ] Thoroughly test the code

**Comment by wolfbeast** [comment]
Required for #22

**Comment by mattatobin** [comment]
Also blocks #7

**Comment by wolfbeast** [comment]
This should be done on a feature branch dedicated to devtools only.

**Comment by wolfbeast** [comment]
Basic functional implementation is working as of commit 224cb6249b0e8ba389104befff4b80f8f5377232 -- Styling is broken which also makes the UI not respond properly to input which is the next step.

**Comment by wolfbeast** [comment]
Most of the devtools work at this point with the proper style changes made. The difficult point will be the checking functionality and fixing it where needed.

**Comment by wolfbeast** [comment]
Apart from a promise failure in the debugger init, all devtools seem to currently be functional.
Testing needed to finish this up -- it's been merged into the master branch.
