### ISSUE TITLE
Re-implement css background-repeat: space|round

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#26]
This will need to be done with directdraw/azure for `space`, which is currently not working as it should. Cairo works. May need to draw on more recent Mozilla implementation for the same that is a WIP now.

**Comment by mattatobin** [comment]
Blocks #33

**Comment by wolfbeast** [comment]
Re-implemented using a different algorithm than before for space. Tested with some simple visual verification.
