### ISSUE TITLE
Bookmarks/history panel is empty

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#28]
After the FE merge, BM/History panel is empty.

SM ran into the same, can draw on those bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1084203
https://bugzilla.mozilla.org/show_bug.cgi?id=1068671
https://bugzilla.mozilla.org/show_bug.cgi?id=1087942

**Comment by wolfbeast** [comment]
Solved by 59207271a79a8ed71bdf608a11c5bb0d23f8affa 832656a2b9867c5dc4b3624ea38be660123feecb and 1484d5bcd741b94c5c5cecb68d947d5228ddb15f

**Comment by mattatobin** [comment]
Blocks #32
