### ISSUE TITLE
Re-implement XSS filter

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#3]
Forward port the XSS filter code

**Comment by mattatobin** [comment]
Blocks #33

**Comment by wolfbeast** [comment]
It doesn't look like the original author of this code will have any time to re-write this for the current code base. We'll likely have to do without the active XSS filter Pale Moon 26 has because it can't easily be ported across without rewriting significant parts of it.

**Comment by mattatobin** [comment]
Well maybe we will get it one day.. Given this was a relatively new Pale Moon feature and there have been some issues with it.. I don't think it should block a first release.. Maybe just consider it something we want to eventually get back..

**Comment by wolfbeast** [comment]
It'll just have to be an enhancement with no milestone.
