### ISSUE TITLE
Fix the findbar (finder) in the FE

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Tycho#30]
Blocks Issue #22 

We need to hook up the new findbar code in toolkit to the browser and get it functional.

**Comment by mattatobin** [comment]
Part 1 does indeed get the findbar working but there are some small problems with it. It isn't really aware of tabswitching in our FE code because we aren't using tab-remoting e10s bs.

It will work on a per-tab basis for actual actions but the status and the search term let alone it's presence isn't exactly aware of changing tabs until we directly tell it to do something.

SeaMonkey had a similar issue they /seemed/ to resolve in [Bug 962910](https://bugzilla.mozilla.org/show_bug.cgi?id=962910)

But it is a little beyond me. I have tried to approximate it without success.

@wolfbeast may be able to interpret for me.

**Comment by mattatobin** [comment]
Ratty indicates the main focus clues for resolving this are in Comments 9, 10, and 11 on [Bug 962910](https://bugzilla.mozilla.org/show_bug.cgi?id=962910) but this will likely need tailored to our tabbrowser.xml

**Comment by wolfbeast** [comment]
Last bits solved in commit 7a1f3b3
