### ISSUE TITLE
Fix the Page (content) Context Menu

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Tycho#31]
Blocks Issue #22 

The context menu when you right-click on page content is busted.

The toolkit jsm module was refactored for e10s and other stupidity Mozilla wanted.

I have worked around the issue in [e096d205572ec808bf0bbccf7cfd9244a2ef739b](https://github.com/binoc-software/tycho-contrib/commit/e096d205572ec808bf0bbccf7cfd9244a2ef739b) (my contrib repo) by including the classical version of PageMenu.jsm locally in browser BUT.. I am not sure if I should actually simply try and fix the code to use the toolkit version or not..

The refactoring Mozilla did included some far out crazy processing with all kinds of json and and e10s checks. Of course it LOOKS LIKE simply fixing it for us would be vaguely trivial but it would execute all that insanity to generate the context menu. While the local version I slipped in simply works and doesn't have any of that junk.

**Comment by mattatobin** [comment]
cfdaf5aaa37e2e7ec9356947dccd29d28651d265

RESOLVED FIXED

**Comment by wolfbeast** [comment]
The Mozilla version has literally completely rewritten all functions and function name and calls.
I'm putting in the classical one in /browser to get a working system ASAP which is my priority at the moment. We can revisit this if the classical context menu somehow (??) doesn't suffice for our needs.

Not sure why this is in /toolkit to begin with; menus are app specific?
