### ISSUE TITLE
Fix Places (Library) in FE

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Tycho#32]
Blocks #22 

Places deals with: Downloads (primary entry point), History, and Bookmarks as such it is a major component with dependencies on the toolkit which has had it's share of refactoring.

Moonchild has already made significant progress to mostly fix this component in: 
59207271a79a8ed71bdf608a11c5bb0d23f8affa, 832656a2b9867c5dc4b3624ea38be660123feecb, and 1484d5bcd741b94c5c5cecb68d947d5228ddb15f

But a few issues remain and should be tracked by a bug... So I created one!

**Comment by wolfbeast** [comment]
The actual places module and handling of downloads (downloads in places), bookmarks and history all works.
The downloads panel is a different/separate component not necessarily linked to the places back-end working or not. Should we track that here too?

**Comment by wolfbeast** [comment]
Downloads has been mostly fixed, anything left there should be handled in a separate issue.
