### ISSUE TITLE
Decide how and actually fix the Charset Menu

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Tycho#34]
Blocks #22 

Mozilla decided on a new way to implement the charset menu in Australis and javascript and subsequently removed the toolkit component we need for this to work.

During the process of traversing the codebases I locally included l10n strings but the functionality remained busted from m-r32 onward and got worse.

We need to either figure out how and to use the new charset menu code or revert the removal of the dependent component and content files from **[this commit](https://hg.mozilla.org/mozilla-central/rev/9eb4f13a78d8)** from [Bug 943252](https://bugzilla.mozilla.org/show_bug.cgi?id=943252)

SeaMonkey uses a different implementation than we do so no real help from their history.

**Comment by mattatobin** [comment]
It should be noted that the View Source window seems to hold at least a minimal implementation of the new CharsetMenu and perhaps with that and diffing a solution can be devised but it is beyond my current capabilities.

**Comment by wolfbeast** [comment]
It's probably best to use the new toolkit version, because ICU/Intl etc. that is part of the new menu implementation.

**Comment by wolfbeast** [comment]
Question. Why exactly do we need this menu anyway? In all my years of browsing the web i have NEVER used it. It should be the task of the websites to define the correct character set
