### ISSUE TITLE
Fix LoginManager

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Tycho#35]
Blocks #22 

Just what it says on the tin.

**Comment by mattatobin** [comment]
Part 1 fixes the event hooks and they are being fired and sent to LoginManager but the browser apparently isn't listening to the notifications back from LoginMananger so while this fixes the errors reported it doesn't resolve the overall issue.

Of NOTE this only affects user/passwords in content (sites) as the non-content credentials seem to be functioning properly.

**Comment by wolfbeast** [comment]
This likely needs some work based on the move to async/json from https://bugzilla.mozilla.org/show_bug.cgi?id=853549

**Comment by wolfbeast** [comment]
Fixed on master with merge d292f6dc46347697c7b2a7c0a70b099807635f51
Tested saving and recalling passwords.
