### ISSUE TITLE
Re-implement WebP decoding

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#4]
Already partially done on the work branch, needs some changes to the decoder cpp

**Comment by mattatobin** [comment]
Blocks #33

**Comment by wolfbeast** [comment]
Mozilla is dragging their feet on this one, despite growing web compatibility. I can't move forward with this without knowing more about the surface cache and image decoding into it that is mostly dbaron's work. https://bugzilla.mozilla.org/show_bug.cgi?id=856375 is where this happens, and it's finally been given some priority - hopefully the work there will give me the background for our own implementation when some code comes in.

**Comment by wolfbeast** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1294490 has a new implementation now at Mozilla's side but that's wholly incompatible with our code (it uses data streams of some sort and is based on what seems to be a complete rewrite of handling the surface cache (the umpteenth version?) )
I've been poking at working around/using the new way of allocating frames in the decoder instead of rasterimage (in place since Gecko 37) but I can't seem to get it to work.
Major suckage; I need help from someone familiar with this code to re-base our decoder properly.
