### ISSUE TITLE
Fix the internal updater

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#44]
Currently the updater doesn't even build (missing .ini)
This also needs thorough testing.

**Comment by wolfbeast** [comment]
Building fixed with previous linked commit.

**Comment by mattatobin** [comment]
Is this still open because removed-files.in hasn't been sorted?

**Comment by wolfbeast** [comment]
Pretty much the only thing left, yes.

**Comment by wolfbeast** [comment]
So.. Mozilla moved old removals to be included in the update manifest in jar files somewhere else. removed-files.in really only has a few overrides in there for things that always need removing or it breaks the update process, but none of the archaic stuff i wanted to cull.

Closing this issue as it's become lower priority as a result for that and we need to move forward. The followup will be a code cleanup issue.
