### ISSUE TITLE
Investigate the use of v38 devtools

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#7]
If we're grafting our front-end on here, it may be possible to use the v38 devtools instead of our previous ones. We need to investigate which of the two is most desirable and most compatible.

**Comment by mattatobin** [comment]
We absolutely will have to use the newer devtools. Our code is not compatible with the devtools toolkit code.

**Comment by wolfbeast** [comment]
Okay. Will have to make sure the FE calls launch the proper devtools components then (I gather more "refactoring" has been done there...)

**Comment by wolfbeast** [comment]
It looks like the v38 devtools can be made to work, so closing this issue - we'll be using the later devtools.
