### ISSUE TITLE
Port media.autoplay.* changes and enhancements from pm-current

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Tycho#92]
We need to port the changes we made to media.autoplay.true and allowscripted over.

Alternatively, [Mozilla Bug 659285](https://bugzilla.mozilla.org/show_bug.cgi?id=659285) has been thrown at a user pointing this out.. It was RESOLVED FIXED with a Target Milestone of mozilla/41..

I don't know which implementation is easier/superior for Tycho but either way.. We should have this.

Blocks #33

**Comment by wolfbeast** [comment]
The Mozilla bug was a starting point for my own fix. The release one should be ported because it offers more control and less of a black&white situation.

**Comment by wolfbeast** [comment]
This needs porting of MoonchildProductions/Pale-Moon@bfc3aa11a30673efc84ab1b338c7ff23d3841eb0 and MoonchildProductions/Pale-Moon@ff764ad471579f6901de2bee266428a454f4eaf0
