### ISSUE TITLE
Mac binaries fail to launch due to runtime linking problems

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Tycho#97]
Something is up with the Mac library paths:

```
[steven@Anesthetize:/Volumes/PaleMoon/PaleMoon.app/Contents/Resources]% ./palemoon-bin 
dyld: Library not loaded: @executable_path/libmozglue.dylib
  Referenced from: /Volumes/PaleMoon/PaleMoon.app/Contents/Resources/./palemoon-bin
  Reason: image not found
zsh: trace trap  ./palemoon-bin
```

todo: try building esr38 and see if it works there, and if so, how the library paths differ

**Comment by mattatobin** [comment]
Blocks #23

**Comment by stevenschlansker** [comment]
Comparing with esr38 (which works fine) It looks like `palemoon` and `palemoon-bin` end up in the `Resources` directory when they should be in `@BINPATH@` instead.  But moving them there by hand doesn't actually fix the problem.  So maybe there's two causes at work here?

**Comment by mattatobin** [comment]
Did esr38 run?

**Comment by stevenschlansker** [comment]
Yes

**Comment by wolfbeast** [comment]
The recent PR to this effect you submitted (PR #89) changed all `@BINPATH@` to `@RESPATH@` -- looks like this is now biting you. I was wondering about this -- on Windows they are equal but obviously not on OSX.

**Comment by stevenschlansker** [comment]
Indeed.  I believe the vast majority of those changes are correct, but clearly I missed at least one.  Reading through that diff in particular to make sure it's right is *really* tough...

**Comment by mattatobin** [comment]
You must know which files go to RESPATH and which go to BINPATH.. Cross-reference the Browser 38 version.
